
# GitHub Actions workflow for managing backend deployment operations
# This workflow includes actions for PHP Laravel and Java
#
name: backend_actions

on:
    push:
        branches: ['deploy-branch'] # Change this to the branch you want to deploy to

jobs:

  ##################################################################
  ################# PHP LARAVEL DEPLOYMENT #########################
  ##################################################################

  # This job will replace the .env file with the .env.production file
  # you can change the branch to {prod-branch} or any other branch you want to deploy to
  replace-env-file:
    runs-on: ubuntu-latest
    needs: check-deploy-version
    steps:
      - name: Checkout prod-branch branch
        uses: actions/checkout@v4
        with:
          ref: prod-branch # Change this to the branch you want to deploy to

      - name: Configure Git
        run: |
          git config --global user.name 'Deploy BOT (CI)'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      # This step will remove the .env.development file if it exists
      # Replace the prod branch with the branch you want to deploy the productions
      - name: Commit and push changes for .env files
        run: |
          git add -f .env
          if [ -f .env.development ]; then
            git add -f .env.development
          fi
          git commit -m "Update .env files for production" || echo "No changes to commit"
          git push origin prod --force

      # This step will replace the .env file with the .env.production file
      # It will also remove the .env.development file if it exists
      - name: Replace .env file with .env.production
        run: |
          if [ -f .env ]; then
            rm .env
          fi
          mv .env.production .env

  # This job will rollback the replaced .env file if the deployment fails 
  # restoring the .env.development file if it exists
  rollback-all:
        if: failure()
        runs-on: ubuntu-latest
        needs: [replace-env-file]
        steps:
            - uses: actions/checkout@v4
              name: Checkout Prod Branch (Rollback)
              with:
                  ref: prod-branch # Change this to the branch you want to deploy to

            - name: Setup Node.js for Rollback
              uses: actions/setup-node@v3
              with:
                  node-version: 20.x
                  cache: 'npm'

            - name: Configure Git for Rollback
              run: |
                  git config --global user.name "GitHub Actions"
                  git config --global user.email "actions@github.com"

            - name: Rollback .env file
              run: |
                  if [ -f .env ]; then
                      rm .env
                  fi
                  mv .env.development .env || echo "No .env.development file to rollback"
                  git add -f .env
                  git commit -m "Rollback .env file" || echo "No changes to commit"
                  git push origin prod-branch --force # Change this to the branch you want to deploy to